### PR TITLE
Added SolutionInfo as central versioning point

### PR DESCRIPTION
**Pull request by dejangeci**
Removed extra stuff from AssemblyInfos and added SolutionInfo as central versioning point so there is no need to update each project separately

### CODE REVIEW

**Comment by zsbzsb** [comment]
So if I understand correctly this allows us to bump the version number from just one file for all projects? And since we are at it, why not move all common attributes (such as product name and copyright) into the same file?

**Comment by dejangeci** [comment]
Yes, correct. I messed up with commits and squashing, so I'll make another pr

**Comment by zsbzsb** [comment]
You don't need to make another PR, after you fix the branch you can force push and everything will be corrected.

**Comment by dejangeci** [comment]
Took too much fiddling with git to get it right. Created a new pr

**Pull request closed without merging**
