### PR TITLE
.Net Standard/Core 2.0 + DllImport Mapping

### PR DESCRIPTION
**Pull request by Balnian**
New PR with DllImport Mapping
Based on #141  (Credits to @Scellow)
- Some Exemples are broken (missing OpenTK for 2.0)
- the visualbasic exemple is back and also broken because of OpenTk... (why is there so much OpenTK in the exemples ???)

### CODE REVIEW

**Comment by LaurentGomila** [comment]
> why is ther so much OpenTK in the exemples ???

Feel free to replace it with a better alternative.

**Comment by Balnian** [comment]
> Feel free to replace it with a better alternative.
It's not about replacing it it's just that i find it weird that the "basic" exemples (window, visualbasic) use OpenTK ... I would have though that they were only the classic SFML tutorial green circle...

**Comment by LaurentGomila** [comment]
> It's not about replacing it it's just that i find it weird that the "basic" exemples (window, visualbasic) use OpenTK ...

These "basic" examples don't use the graphics module, they show how to use SFML for pure OpenGL rendering.

**Comment by dabbertorres** [comment]
I wrote a stupid-simple minimal OpenGL wrapper for examples/opengl, could go that route.

[Wrapper](https://github.com/dabbertorres/SFML.Net/blob/remove-opentk/examples/opengl/OpenGL.cs)
[Main](https://github.com/dabbertorres/SFML.Net/blob/remove-opentk/examples/opengl/Program.cs), barely changed.

**Comment by avantimaestro** [comment]
Alright, how is this project going? What's finished and what still needs to be done? Can someone give me a quick recap?

**Comment by Balnian** [comment]
OpenTK is not .Net Standard 2.0 yet, @dabbertorres has a wrapper to maybe replace the OpenTK dependency.
I could not try my PR on Linux because i'm on a VM and OpenGL is broken (VirtualBox). The VB exemple project (and others) is broken because of OpenTK not being available... Thats about it, i think.

**Comment by avantimaestro** [comment]
So basically as long as we don't find a way to replace OpenTK, we're stuck, right?

**Comment by WarpspeedSCP** [comment]
But there aren't any alternatives to OpenTK, are there? Things like sharpDX only work on windows!

**Comment by avantimaestro** [comment]
I have to admit, I am not familiar with how the wrapper provided by @dabbertorres works, but, if I understood correctly, it would remove OpenTK from the equation completely.

**Comment by avantimaestro** [comment]
It looks like writing our own wrapper for OpenGL should do the trick or did I get something wrong?

**Comment by dabbertorres** [comment]
I think so.

The simple wrapper I linked above is a very simple PInvoke layer accessing the Windows (where I wrote it) OpenGL library (OpenGL32.dll), while providing a more-or-less C# API.
I basically replaced the calls to OpenTK with the same call to my wrapper.
It needs testing. I haven't had much time to work on it/this. As I recall, I had an issue with it, which is why I haven't pushed it much.

The other option, as @LaurentGomila mentioned, is remove the OpenGL examples. As that isn't really a SFML problem. After all, it's essentially the same path as using OpenGL with SFML's C++ API.

So, in my mind, we need some level of community input on preference in regards to the above options, or @LaurentGomila to make an executive decision, as he is the repository's owner.

**Comment by avantimaestro** [comment]
Just to be clear: SFML.Net as we have it now works and .NET Core applications can use it. The problem is that using OpenTK directly inside a .NET Core app does not work, that's why the examples are broken, is that correct?

**Comment by dabbertorres** [comment]
Unless @Balnian has anything else, I believe you are correct.

I started cleaning up my little wrapper from above - I've got a fair amount of time to work on it.

**Comment by LaurentGomila** [comment]
> So, in my mind, we need some level of community input on preference in regards to the above options, or @LaurentGomila to make an executive decision, as he is the repository's owner.

Even if it's not a SFML problem, it's still nice to demonstrate how to combine SFML and OpenGL. Is there really no simple/standard way to use OpenGL in a .Net app?? If not, then we may remove the OpenGL examples, yes.

**Comment by avantimaestro** [comment]
@dabbertorres I don't think investing time into the wrapper is a good idea. It's way too much work to be worth it, and there's also the problem that we would have to get it running on all platforms, not only Windows.

**Comment by dabbertorres** [comment]
> Even if it's not a SFML problem, it's still nice to demonstrate how to combine SFML and OpenGL. Is there really no simple/standard way to use OpenGL in a .Net app?? If not, then we may remove the OpenGL examples, yes.
I agree it'd be nice to demonstrate. But I do not know of or have seen/found a simple/standard method. OpenTK is the most standard I've seen, but it's a big dependency and such.

> @dabbertorres I don't think investing time into the wrapper is a good idea. It's way too much work to be worth it, and there's also the problem that we would have to get it running on all platforms, not only Windows.
Oh I completely agree. No argument here!

Well then, may I say this qualifies as for removing the OpenGL examples?
@Balnian, feel free to go ahead and remove it.

**Comment by avantimaestro** [comment]
If there is anything else left to do let us know.

**Comment by dabbertorres** [comment]
Tested on Ubuntu 16.04 so far, with dotnet-sdk-2.0.0 from [MS' repo](https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod), with CSFML and SFML masters compiled with g++ 7.2.0.

examples:

shader: seems to run great.

sound: plays the Sound and Music correctly, but the PlayingOffset is only printed once the sound has stopped playing, and it seems Time's toString() method is broken?
output: `Playing... SFML.System.Time sec`
Also, I got `AL lib: (EE) alc_cleanup: 1 device not closed` after the Music file finished (though that might be due to nondeterministic .net garbage collection ordering). 

sound_capture: I don't have a mic with this box (at work), so I couldn't really test, but it runs!

The rest use OpenTK, so I couldn't run them.

For using less OpenTK, may want to consider rewriting the VB example to...not use OpenTK. Just a simple draw a sprite or something.

**Comment by Balnian** [comment]
There will need to be changes made to how i did the OS/platform detection in the system .csproj, because on macOS the OS value is "Unix" which is not the expected value so it default to loading the Linux csfml files (.so)

**Comment by Balnian** [comment]
Since it's been a while, i would like to know what do you feel should be the criteria to merge this PR?

- Works on Windows, Mac, Linux
- Works/tested on Windows ONLY (same as current repo?)
- Works on Windows, Linux (because we cannot test Mac?)
...

Please express your opinion!!!

Do you feel this deserve a forum post to get wider input from the comunity?

**Comment by dabbertorres** [comment]
Making a forum post can't hurt, and given some time, is usually visible to more people. I'd say do it.

Ideally, it'd be best to test on all SFML supported platforms. Windows and Linux are easy.
@eXpl0it3r has a Mac Mini, iirc. Could that be used for testing on OSX, @eXpl0it3r ?

I think that'd be doable, and cover general needs.

**Comment by Balnian** [comment]
Did the forum post [Here](https://en.sfml-dev.org/forums/index.php?topic=22808.0)
So reply on the forum for the criteria, it will be easier if it's in a single place

**Comment by kevin192291** [comment]
Hello, is there any update on the status of this? I would love to see this working! C# dotnet Core + SFML would be amazing!

**Comment by Balnian** [comment]
Right now it's working for Windows and Linux. MacOS  is not really tested.
And everything related to OpenTK doesn't work because they didn't do a Dotnet Core release yet.
But feel free to use it, there shouldn't be alot of bug (no more than what the binding already have) and if you find a bug report it

**Comment by dabbertorres** [comment]
@eXpl0it3r, would you be able to test on OSX with that Mac Mini from the fundraiser a while back?

**Comment by eXpl0it3r** [comment]
In theory yes, in practice, I've no idea what steps are needed to use .NET on macOS or SFML.NET for that matter...

**Comment by Balnian** [comment]
@eXpl0it3r you will need:
  Dotnet Core runtime https://www.microsoft.com/net/download/
Go to the sfml.net directory in your mac,
And execute the command : "dotnet restore" once, then "dotnet build" and finaly "dotnet run" 
I'll suggest you do all these step in the exemple/shader/  directory this is a working test on all other platforms.
*Before "dotnet run" you must add csfml dylib in the output ditectory

**Comment by Balnian** [comment]
@kevin192291 it's normal that these two don't work, they require OpenTK which doesn't have a Dotnet Core build at the moment.
And yes if you have time to test it on mac to it would be awesome!!

**Comment by dabbertorres** [comment]
@eXpl0it3r If it'd help, I can hop on irc or something this weekend and help get it setup.

**Comment by avantimaestro** [comment]
`CPointer = sfShader_createFromStream(vertexAdaptor.InputStreamPtr, geometryAdaptor.InputStreamPtr, fragmentAdaptor.InputStreamPtr);`
in Shader.cs should be
`CPointer = sfShader_createFromStream(vertexAdaptor != null ? vertexAdaptor.InputStreamPtr : IntPtr.Zero, geometryAdaptor != null ? geometryAdaptor.InputStreamPtr : IntPtr.Zero, fragmentAdaptor != null ? fragmentAdaptor.InputStreamPtr : IntPtr.Zero);`

sorry for not doing it myself, but sadly i am not good with git...

**Comment by dsoronda** [comment]
Hey guys, I created new unofficial fork named [SFML.Netstandard](https://github.com/dsoronda/SFML.Netstandard) and converted all projects to Netstandard platform.

My plan is to keep this SFML.Net for legacy .NET framework and use SFML.Netstandard for new .NET Core projects. Is anyone available to help me out ?

It would be nice to make it official fork one day.

Cheers.

**Comment by Scellow** [comment]
I think that's the best idea @dsoronda because at this rate this PR will be merged in 10 years..

**Comment by LaurentGomila** [comment]
I'm clearly unable to follow the latest evolutions of the .Net ecosystem, and thus, to maintain this repository and the various PRs that it receives. So yes, maybe we should give up trying to maintain an "official" binding and instead let forks live their own live.

**Comment by Balnian** [comment]
I also feel a bit frustrated at the slowness at which this PR has progressed...
But personally i would prefer to keep this SFML.Net(standard) an "official" repo because it makes users feel safer, or at least made me at first, using it. Even if @LaurentGomila you have problems keeping up I think that as a team, we did pretty good work:
- Did a full conversion to .Net Standard 2.0
- added support for various OS
- tried to get feedback and involve the small community of SFML.Net (as much as we could)

Also, this kind of work is not something that should happen often, from what it look, the Standard 2.0 will be compatible with all future .Net Core releases, so after this we will go back to only update the library when there's a bug found or a new SFML release (except for the fabled SFML 3.0 😉 which should require a rewrite).

Like I said I would prefer to keep this an "official" binding, but I also feel creating an org (as suggested by @dabbertorres ) would simplify everything and reduce the burden on @LaurentGomila (would it be possible to do both? like giving Laurent a title or some access in the org to keep this official, but still have others running the org? i don't know how this work 😅 )

On the other hand, if Laurent agrees, we could also transfer SFML.Net to the org to again reduce the burden on Laurent and have one place for the SFM.Net community to look at.

Returning to @dsoronda fork, I would have preferred that this PR was used, because the fork is not currently compatible with Linux or MacOS (which implies redoing a lot of work that exist in this PR) but still great job 👍 

Also to avoid dragging this too long, I think it's clear from my [last attempt](https://en.sfml-dev.org/forums/index.php?topic=22808.0) to get feedback from the community (where only eXpl0it3r said something) that we who are discussing here, should just go forward with a vote and take action accordingly.

The way I see it, there are 3 options:

1. We merge this PR and continue from here
2. We create an org to manage a new binding (SFML.NetStandard)
3. Do nothing (as a community) and let everyone do their own forks of SFML.Net to make a Net Standard binding

It may sound extreme, but I feel we should make a decision soon and start moving again as soon as we can or else i have a feeling this will just die and default to option 3.

**Comment by dsoronda** [comment]
How about this guys?

Instead of merging big changes from [PR143] (https://github.com/SFML/SFML.Net/pull/143) that have merge conflict, I suggest following steps:

1. Merge [PR 150](https://github.com/SFML/SFML.Net/pull/150). This change only adds VS 2017 Solution into branch and fixes nuget references so code still buils properly in VS 2017.

2. Create new issue/PR to replace Window example with my [SimpleWindow.cs example](https://github.com/dsoronda/SFML.Netstandard/blob/master/examples/SimpleWindow/Program.cs) so we could remove dependencies of OpenTK in that example and keep OpenTK in OpenGL example project.

3. Add new .NET Core Solution in build directory ie. VsCore and reference additional .NET Standard Project files in src/example folders ie. sfml-window_core.csproj. This way we could keep old projects for .NET Framework and still build for Netstandard.

4. Add other PR changes

5. If/when all changes work, replace old nuget package with new one. I belive that it can contain both frameworks in one nuget. It would be nice if we could have SFML.Net-linux/windows/mac nuget packages with native sfml dlls for each platform.

5. Profit ;)

Just to note that there is [OpenTK.NETCore nuget package](https://www.nuget.org/packages/OpenTK.NETCore/) that we could use but I have problems with it (Error reading protected memory).

I belive that we (as community) could easily help @LaurentGomila with code review and technical stuff.

**Comment by LaurentGomila** [comment]
Looks like a good plan, but:

> Add new .NET Core Solution in build directory ie. VsCore and reference additional .NET Standard Project files in src/example folders ie. sfml-window_core.csproj. This way we could keep old projects for .NET Framework and still build for Netstandard.

What does this mean exactly? Would we have to maintain two sets of sources/projects within the same repository?

**Comment by dsoronda** [comment]
> Add new .NET Core Solution in build directory ie. VsCore and reference additional .NET Standard Project files in src/example folders ie. sfml-window_core.csproj. This way we could keep old projects for .NET Framework and still build for Netstandard.

What i meant with this:

- Create new /src/Window/sfml-window_core.csproj (Netstandard project). Simple `d:\work\github\SFML.Net\src\Window>dotnet new classlib -n sfml-window_core.csproj -o . ` will do.
- Create new /build/SfmlCore/SfmlCore.sln and reference new project files.

~~~shell
cd /build/
dotnet new sln -n SfmlCore -o SfmlCore
cd SfmlCore
dotnet sln SfmlCore.sln add ..\..\src\Window\sfml-window_core.csproj.csproj
...
~~~

This way we can keep old project files (still walid for VS 2013/2017) and have new solution for Netstandard.
Both projects will reference same C# code but build different assemblies in bin folder, ie.
`\SFML.Netstandard\src\Window\bin\Debug\netstandard2.0\` vs `\SFML.Netstandard\src\Window\bin\Debug\`

I just copied old code from src into my fork and fixed project references and it works. So I don't expect any problems with this approach.

**Comment by LaurentGomila** [comment]
So it's just about project settings, the source code can be the exact same for both?

**Comment by dsoronda** [comment]
@LaurentGomila,
I can confirm that this works for projects in /src folder.

I updated my [PR 150](https://github.com/SFML/SFML.Net/pull/150) with new changes so anyone can take a look and review changes.

One note: there are issues with VS 2017 and building Core project , so you have to build it manually from `\build\SfmlCore` with command `dotnet build`. 

You may create new branch called `core2` so i could direct PR to that branch so anyone can test it for braking changes.

I'll continue to do same for projects examples folder.

**Comment by dsoronda** [comment]
I  basically done steps 1-3 in [PR 150](https://github.com/SFML/SFML.Net/pull/150/commits) and now there are both old and new Netstandard projects ( except VB, I don't use it and not sure that it works in .NET Core).

I tested and all projects builds properly.
There is bug in \example\shader\shader.cs that throws exception: 'Failed to load shader from file  resources/pixelate.frag'. Mabye someone can take a look on that error ?

Also I added references to OpenTK.NETCore nuget package.

All changes are visible on master branch on my fork of [SFML.Net](https://github.com/dsoronda/SFML.Net) so feel free to test/code review/PR it.

**Comment by Balnian** [comment]
Saddly, it's not just project settings, we have to modify things so we can link to CSFML naming scheme on Linux and MacOS (but there might be a way to salvage this by defaulting to Windows). Also i'm not a big fan of duplication of code, but mayve i don't understand/can visualize what you mean 

Also the current merge conflict is litteraly 2 indentation on two libes of code... I was just lazy :wink:

**Comment by dsoronda** [comment]
I tested Core solution on Linux (Lubuntu 17.10) and it builds properly.

I'm not sure how to get Linux CSFM libraries and use it in project. Any suggestion ?

I get this error : Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'csfml-graphics-2'

**Comment by Balnian** [comment]
>I'm not sure how to get Linux CSFM libraries and use it in project. Any suggestion ?
I get this error : Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'csfml-graphics-2' 

That's exactly the problem i was talking about and that we solved :wink:  (there's a reason that I named this PR "**+Dllimport Mapping** ")

>I tested Core solution on Linux (Lubuntu 17.10) and it builds properly.

What do you mean? You tested .Net Core?   

> I'm not sure how to get Linux CSFM libraries and use it in project. Any suggestion ?

You need to buid them from CSFML source if i remember correctly, because the precompiled version don't work

**Comment by dabbertorres** [comment]
> I have nothing against keeping it official on this repository. The thing is, I am unable to review technical stuff, so I have to blindly rely on you guys. So I can merge stuff and maintain this repository, but you all have to agree and give me a clear "ok let's merge it" for things to move on. As long as PRs are being discussed, or no feedback is given, I can't do anything.
https://github.com/SFML/SFML.Net/pull/143#issuecomment-367941283

https://github.com/SFML/SFML.Net/issues/151

**Comment by dsoronda** [comment]
>> I'm not sure how to get Linux CSFM libraries and use it in project. Any suggestion ?
I get this error : Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'csfml-graphics-2'

> That's exactly the problem i was talking about and that we solved 😉 (there's a reason that I named this PR "+Dllimport Mapping ")

Well, I fixed this with importing @Balnian changes into my test branch. Solution is building properly but still can't make window example to work :(

~~~
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libcsfml-graphics.so': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at SFML.Graphics.RenderWindow.sfRenderWindow_createUnicode(VideoMode Mode, IntPtr Title, Styles Style, ContextSettings& Params)
   at SFML.Graphics.RenderWindow..ctor(VideoMode mode, String title, Styles style, ContextSettings settings) in /home/user/work/SFML.Net/src/Graphics/RenderWindow.cs:line 62
~~~

I copied all .so files from CSFML-2.2/lib into build directory but still got same error. Maybe I'm missing some other references or I need to build CSFML 2.4 ?

**Comment by Balnian** [comment]
try building csfml from source @dsoronda and yes you need 2.4

**Comment by dsoronda** [comment]
I builded csfml 2.4 on linux and now i get this error when run `dotnet window.dll`

`“dotnet window.dll” terminated by signal SIGSEGV (Address boundary error)`

It's same for all examples, so i'm not sure is it problem with my CSFM build or somehting else.

If anyone else wanna try it on Linux/os X, here is link to [test branch](https://github.com/dsoronda/SFML.Net/tree/multiplatform_support) before I merge it to my master.

**Comment by Balnian** [comment]
What if you just  `dotnet run` in one of your exemple project?

**Comment by dsoronda** [comment]
@Balnian 
Well, that's exactly what I did. Created all .so files, copied them to examples\window\bin\debug\netstandard2.0\ and then run `dotnet window.dll` in that directory.

Error is same for all examples. 
Code works properly on Windows.

**Comment by dabbertorres** [comment]
The examples (shader, sound, sound_capture, window) on that branch all run successfully for me on Ubuntu 16.04.4.
All I did was (from an example's directory): `dotnet run -p <example>_core.csproj`

**Comment by Kaev** [comment]
Thank you all for your work. Really sad that it takes so long to get this awesome project on the correct path. If i could vote, i would vote for an organization aswell.
I used SFML.NET in the past several times but now i don't know which one i should use.
This MR? Any other of the mentioned MRs? The mentioned fork?
Any help is appreciated. :)

**Comment by dsoronda** [comment]
@Kaev 
If you need .NET Framework version you can stick with this branch.
If you need .NET Standard version you can clone & build this [version](https://github.com/dsoronda/SFML.Net). It's up to date with master branch and includes fixes for .NET Standard and some new OpenGL and Paint examples. It's also tested on Windows & Linux.

I hope that @Balnian, @texus, @LaurentGomila and **others** could take a look on my PR #150 so we could finally merge it and move on?

**Comment by Balnian** [comment]
@dsoronda 
I didn't see all this activity on #150 , great job! I should have some free time in the coming weeks to check it out!

**Comment by eXpl0it3r** [comment]
I think we need to tackle things one step at a time. First let's decided whether we *really* want to keep .NET Framework projects around.

Please discuss that topic on the forum thread: https://en.sfml-dev.org/forums/index.php?topic=24345.0

@Balnian @dabbertorres @dsoronda

**Comment by dsoronda** [comment]
I'll try to answer some of this questions here since I don't have forum account.

IMHO:

> Do we want to keep supporting .NET Framework?
No. We have .NET Core as successor for .NET Framework with native support on all major plaftorms (Win/Linux/OSX)

> What are the advantages of keeping support for the .NET Framework?
None.

> Are we going to support .NET Core only?
Yes,

> Are we supporting .NET Core 2 or also any other version?
We should keep supporting .NET Core 2.0+ versions

> What are the advantages of .NET Core 2?
Speed, "native" multi-platform support (vs Mono), support for future versions, etc.

I think there is some misunderstanding here about different .NET versions.
All libraries here are **.NET Standard v2.0** version not .NET Core libraries.

.NET Core standard libraries can be used **BOTH** in .NET Core and .NET Standard. Here are list of [supported framework versions](https://docs.microsoft.com/en-us/dotnet/standard/frameworks).
Just to note, **opposite doesn't stand, .NET Framework assemblies are not fully supported in .NET Core**.

So, to summaries why we need this PR. We use it to build .NET Standard libraries and reference them in both .NET Core & .NET Framework applications (as nuget package). Currently we can not use them in .NET Core application.

Just for reminder, changes in this PR are almost zero in code (some labda refactoring etc.) and a lot of changes in project files (they are not same for .NET framework vs .NET Standard/Core) and how project is published (nuget).

Here are some helpful links about different libraries:

- [What is the difference between .NET Core and .NET Standard Class Library project types?
](
https://stackoverflow.com/questions/42939454/what-is-the-difference-between-net-core-and-net-standard-class-library-project)
- [MSDN - .NET Standard - Demystifying .NET Core and .NET Standard]
(https://msdn.microsoft.com/en-us/magazine/mt842506.aspx)
- and this [.NET Core vs .NET Framework: How to Pick a .NET Runtime for an Application](https://stackify.com/net-core-vs-net-framework/).

I hope this will clarify why we are trying to ditch old .NET Framework.

@Balnian , @dabbertorres  @eXpl0it3r 

You are always welcomed to try my fork for testing before approving this PR (I really hope that you will, so that we can polish any problems before merge).

Cheers

**Comment by dsoronda** [comment]
We can close this one now. :)

**Comment by Balnian** [comment]
:tada:

**Pull request closed without merging**
