### PR TITLE
Allow passing null streams to Shader

### PR DESCRIPTION
**Pull request by Slko**
See #127

### CODE REVIEW

**Comment by zsbzsb** [comment]
Why not just utilize a ternary operator and avoid duplicating code?

```csharp
StreamAdaptor vertexAdaptor = vertexShaderStream != null ? new StreamAdaptor(vertexShaderStream) : null;
StreamAdaptor fragmentAdaptor = fragmentShaderStream != null ? new StreamAdaptor(fragmentShaderStream) : null;
CPointer = sfShader_createFromStream(vertexAdaptor != null ? vertexAdaptor.InputStreamPtr : IntPtr.Zero,
                                     fragmentAdaptor != null ? fragmentAdaptor.InputStreamPtr : IntPtr.Zero);
if (vertexAdaptor != null) vertexAdaptor.Dispose();
if (fragmentAdaptor != null) fragmentAdaptor.Dispose();
```

**Comment by Slko** [comment]
The first version of my code looked like yours, but don't you think it's a mess? The only clean way I found was that one (which was inspired by the source code of sfShader_createFromStream, actually).
Other than that, both are okay.

**Comment by zsbzsb** [comment]
>The first version of my code looked like yours, but don't you think it's a mess?

I personally like to try to avoid code duplication and IMO this situation is perfect for ternary operators.

>The only clean way I found was that one (which was inspired by the source code of ```sfShader_createFromStream```, actually).

I guess since it is already coded this way in CSFML we can keep the same style for consistency in SFML.Net.

>Other than that, both are okay.

Since I am fine with the changes now as is @LaurentGomila do you want to review this before I merge it?

**Comment by LaurentGomila** [comment]
It looks good. So *if it has properly been tested*, it can be merged.

**Pull request merged**
